### PR TITLE
2017 website

### PR DESCRIPTION
**Pull request by listochkin**
- set dates and location
 - switched from "mostly blue" to "mostly purple"
 - switched CoC to Conf CoC (that one has Russian translation)
 - removed accessibility statement until we examine the venue properly
 - moved Katharina to advisors

[You can see the front page here](https://listochkin.github.io/2017.rustfest.eu/) but GH Pages won't append `/2017.rustfest.eu/` to links, and some assets might be invisible because of that. Once it runs on a domain root it will work fine.

### CODE REVIEW

**Comment by listochkin** [comment]
Also, [see another PR for CFP app](https://github.com/RustFestEU/call4papers/pull/6)

**Comment by katsel** [comment]
Looks very good @listochkin! Thanks for your work.
I would suggest to remove `origami.html` and `socks.html` as well (these are leftovers from 2016), and completely remove the accessibility statement file `accessibility.md`, so it is completely offline. It can be re-added later at any time, when needed.

**Comment by listochkin** [comment]
@katsel done

**Comment by katsel** [comment]
Perfect, +1 from my side.

**Comment by gnunicorn** [comment]
@listochkin perfect. Thanks.

Could we add the travel page/info about the location already, too?

**Comment by gnunicorn** [comment]
also realised we need a new solution for how to include blog post - if they are now in a separate subdomain...

- @listochkin  [ ] please remove the `_posts` from the repo, too

**Pull request merged**
