### PR TITLE
Correcting Social Media Links for Manish

### PR DESCRIPTION
**Pull request by ioana-chiorean**
I saw on website that they are pointing to http://2017.rustfest.eu/ so I think this should fix it.

PS: I wanted to try a fix too, not only to log the bug.

### CODE REVIEW

**Comment by katsel** [comment]
Hmm @ioana-chiorean thank you for noticing that!
You're right - the `href` attribute of the links is empty. I just tried out your patch with `bundle exec jekyll serve` locally, but it seems like the `href` is still empty. Does anyone else from the RustFest team know what this is about?

**Comment by katsel** [comment]
OK, I think I found it.
The fix needs to be made in the file `_data/speakers.yml`. @gnunicorn wrote `url` instead of `link`.

So the fix would be to change the `url` in line 8 and 12 to `link`. The change in `index.html` is not necessary then.

Would you like to correct that, @ioana-chiorean? You're the one who found that error. 😊

**Comment by ioana-chiorean** [comment]
@katsel I've updated the files. Let's try this again 👓 

Thanks for the help! 🙇‍♀️

**Comment by katsel** [comment]
The changes are live now (and I need to practice merging 😝).
💪 Thank you!

**Comment by ioana-chiorean** [comment]
🎉  Happy to help!

**Pull request merged**
