### PR TITLE
Adding sponsorship packages

### PR DESCRIPTION
**Pull request by gnunicorn**
Here is my first proposal for Sponsorship packages. Rendered it looks like this:

screen shot 2017-02-26 at 15 58 20-fullpage

Changelog:

 - Made it a webpage
 - Removed Tote-Bag-Stuff (as we didn't provide it)
 - added Video and promotional stuff
 - added more details on On-side-stuff
 - Clarify what the Sponsor provides and what we provide
 - Clarify that all this is VAT excluded
 - resort to make Platinum pop more

### CODE REVIEW

**Comment by gnunicorn** [comment]
@listochkin Can you please let me know if we can provide tables, standing tables, something that the Companies could use as "their area"?

@Hoverbear this is my first proposal. What do you think?

**Comment by Hoverbear** [comment]
What is the `**` for `Dedicated Company Area**`?

**Comment by Hoverbear** [comment]
Also, can we have a consistent usage for the city name? Is it `Kiyv`? `Kiev`? `Київ`? `Киев`?

**Comment by gnunicorn** [comment]
Dedicated company area: a standing table or something, similar to what we
had last time. Depends on the venue, hence the vagueness. But essentially
saying you get a corner.

The official writing we use is kiyv. If we have any other version, we
should replace it!

(At the dentist atm, will check the commit again after)

**Comment by Hoverbear** [comment]
Okay, we should have that down at the bottom explaining it, right now we just have `**` with no explanation of what it means.

**Comment by gnunicorn** [comment]
waiting for @listochkin to tell us what we can offer, then we can add what that really means.

**Comment by Hoverbear** [comment]
Okay. Otherwise LGTM. 

@flaki mentioned something on Twitter about costs.

**Comment by listochkin** [comment]
@gnunicorn they have plenty of tables. There's a part of main hall area that we can use for sponsors.

**Comment by gnunicorn** [comment]
@hoverbear, added the details.

Also, what do you think about these names instead of the olympia-relation? I'm also happy to use other names (or those in a different order - not a native speaker), but I felt like something more community and positive would be nice. Open to proposals (but please pick three that all start with different letters to avoid confusion).

screen shot 2017-02-27 at 23 29 53-fullpage

**Comment by Hoverbear** [comment]
Given that we're asking for corporate sponsorship I think keeping it simple with gold/silver/etc is simplest. Using terms like "Badass" might turn away some sponsors.

It's important to use things with a straightforward hierarchy if we do choose to use another scheme, though. There is nothing to tell me "Prime" is better than "Badass", for example.

**Comment by gnunicorn** [comment]
fair enough. However, should we at least use metals, that rust ;) ?

**Comment by gnunicorn** [comment]
Declaring "bikeshedding" -- reverted the names to what it was before and mergin as is.

**Comment by gnunicorn** [comment]
@Hoverbear do you still need a screenshot of the latest version to send around or is the (hidden) link enough?

**Comment by Hoverbear** [comment]
The link is fine. :)

**Pull request merged**
